Remove google chrome from the moc-xdmod docker image
CCI-MOC/xdmod-cntr pull request #129
Opened 2023-01-30 19:50 UTC by rob-baron

As google chrome is only used to run their UI tests and we are not yet developing anything related to the UI so we don't need to refer to google chorme in the dockerfile.

2023-01-30 19:56 UTC, knikolla requested changes
Please remove the repo as well, on line 4. And from the assets folder. 

EDITED: to also mention removing from assets folder.

2023-01-30 20:58 UTC, rob-baron commented
ok, the repo is removed from line 4

2023-01-30 23:04 UTC, larsks approved these changes

2023-01-31 16:40 UTC, knikolla approved these changes

2023-01-31 16:40 UTC, merged