Moved time of xdmod openshift cron job
CCI-MOC/xdmod-cntr pull request #182
Opened 2023-06-05 18:14 UTC by tzumainn

The job currently runs at 1am; however 1am server time is apparently 9pm the previous day OpenShift time. Changing the time to 1pm will allow the job to get all the data for the previous day.

2023-06-05 18:15 UTC, tzumainn commented
@rob-baron Let me know what you think! If this is okay, after this is merged can you also push the change live?

2023-06-05 19:18 UTC, rob-baron requested changes
Lets also move the time that the ingestor runs to around 2:00, as this PR implies that.

2023-06-05 19:22 UTC, tzumainn commented
> Lets also move the time that the ingestor runs to around 2:00, as this PR implies that.

Sounds good! I've updated the time.

2023-06-06 00:25 UTC, rob-baron approved these changes
Look good.

2023-06-06 00:26 UTC, merged